services:
  api:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - postgres
    environment:
      ConnectionStrings__Default: "Host=postgres;Database=todo;Username=postgres;Password=password"

  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: "password"
      POSTGRES_DB: "todo"
    ports:
      - "5432:5432"
